[package]
name = "pkms-task"
version = "2.3.6"
description = "Task management logic for pkms"
edition = "2024"
license = "MIT"

[lints]
workspace = true

[dependencies]
anyhow = "1"
chrono = { version = "0.4", default-features = false, features = ["clock", "serde", "std"] }
pkms-org = { path = "../pkms-org" }
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
tempfile = "3"
