[package]
name = "pkms-task"
version = "1.12.3"
description = "Task management logic for pkms"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = "1"
chrono = { version = "0.4", default-features = false, features = ["clock", "serde", "std"] }
pkms-org = { path = "../pkms-org" }
serde = { version = "1", features = ["derive"] }
