[workspace]
members = [
    "crates/pkms",
    "crates/pkms-db",
    "crates/pkms-org",
    "crates/pkms-rag",
    "crates/pkms-task",
    "crates/pkms-tokens",
    "crates/pkms-web",
]
default-members = ["crates/pkms"]
resolver = "3"

[workspace.lints.clippy]
# unnecessary_wraps = "warn"
unused_self = "warn"
option_option = "warn"

needless_pass_by_value = "warn"
needless_pass_by_ref_mut = "warn"
ptr_arg = "warn"
trivially_copy_pass_by_ref = "warn"
large_types_passed_by_value = "warn"

# Exceptions must be deliberate
allow_attributes_without_reason = "deny"

# Local readability
wildcard_imports = "warn"
enum_glob_use = "warn"
