[workspace]
members = [
    "crates/pkms",
    "crates/pkms-db",
    "crates/pkms-org",
    "crates/pkms-rag",
    "crates/pkms-task",
    "crates/pkms-tokens",
    "crates/pkms-web",
]
default-members = ["crates/pkms"]
resolver = "3"

[workspace.lints.clippy]
# unnecessary_wraps = "warn"
unused_self = "warn"
option_option = "warn"
