use super::*;
#[test]
fn test_all_commands_json() {
    let (_dir, root) = setup_db();
    let db = root.to_str().unwrap().to_string();
    let cases: Vec<(Vec<String>, bool)> = vec![
        (
            vec![
                "--db".into(),
                db.clone(),
                "--output-format".into(),
                "json".into(),
                "check".into(),
            ],
            false,
        ),
        (
            vec![
                "--db".into(),
                db.clone(),
                "--output-format".into(),
                "json".into(),
                "stats".into(),
            ],
            true,
        ),
        (
            vec![
                "--db".into(),
                db.clone(),
                "--output-format".into(),
                "json".into(),
                "orphans".into(),
            ],
            true,
        ),
        (
            vec![
                "--db".into(),
                db.clone(),
                "--output-format".into(),
                "json".into(),
                "check".into(),
                "--file-links".into(),
                "--attachment-links".into(),
                "--id-links".into(),
            ],
            false,
        ),
        (
            vec![
                "--db".into(),
                db.clone(),
                "--output-format".into(),
                "json".into(),
                "stats".into(),
                "--hubs".into(),
            ],
            true,
        ),
        (
            vec![
                "--db".into(),
                db.clone(),
                "--output-format".into(),
                "json".into(),
                "stats".into(),
                "--tags".into(),
            ],
            true,
        ),
        (
            vec![
                "--db".into(),
                db.clone(),
                "--output-format".into(),
                "json".into(),
                "info".into(),
            ],
            true,
        ),
        (
            vec![
                "--db".into(),
                db.clone(),
                "--output-format".into(),
                "json".into(),
                "resolve".into(),
                "--title".into(),
                "Note".into(),
            ],
            true,
        ),
        (
            vec![
                "--db".into(),
                db.clone(),
                "--output-format".into(),
                "json".into(),
                "query".into(),
                "Note".into(),
            ],
            true,
        ),
        (
            vec![
                "--db".into(),
                db.clone(),
                "--output-format".into(),
                "json".into(),
                "path".into(),
                "Note A".into(),
                "Note C".into(),
            ],
            true,
        ),
        (
            vec![
                "--db".into(),
                db.clone(),
                "--output-format".into(),
                "json".into(),
                "context".into(),
                "Note A".into(),
                "--depth".into(),
                "1".into(),
            ],
            true,
        ),
        (
            vec![
                "--db".into(),
                db.clone(),
                "--output-format".into(),
                "json".into(),
                "validate".into(),
                "Note A".into(),
            ],
            true,
        ),
        (
            vec![
                "--db".into(),
                db.clone(),
                "--output-format".into(),
                "json".into(),
                "get".into(),
                "Note A".into(),
                "--links".into(),
            ],
            true,
        ),
        (
            vec![
                "--db".into(),
                db.clone(),
                "--output-format".into(),
                "json".into(),
                "suggest".into(),
                "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa".into(),
            ],
            true,
        ),
        (
            vec![
                "--db".into(),
                db.clone(),
                "--output-format".into(),
                "json".into(),
                "new".into(),
                "Parametric Test".into(),
            ],
            true,
        ),
        (
            vec![
                "--db".into(),
                db.clone(),
                "--output-format".into(),
                "json".into(),
                "fix".into(),
                "ffffffff-ffff-4fff-ffff-ffffffffffff".into(),
                "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa".into(),
            ],
            true,
        ),
        (
            vec![
                "--db".into(),
                db.clone(),
                "--output-format".into(),
                "json".into(),
                "task".into(),
                "agenda".into(),
            ],
            true,
        ),
        (
            vec![
                "--db".into(),
                db.clone(),
                "--output-format".into(),
                "json".into(),
                "task".into(),
                "list".into(),
            ],
            true,
        ),
        (
            vec![
                "--db".into(),
                db.clone(),
                "--output-format".into(),
                "json".into(),
                "stats".into(),
                "--todos".into(),
            ],
            true,
        ),
        (
            vec![
                "--db".into(),
                db.clone(),
                "--output-format".into(),
                "json".into(),
                "check".into(),
                "--filetags".into(),
            ],
            false,
        ),
        (
            vec![
                "--db".into(),
                db.clone(),
                "--output-format".into(),
                "json".into(),
                "task".into(),
                "p1".into(),
                "show".into(),
            ],
            true,
        ),
    ];
    for (args, expect_success) in &cases {
        let args_refs: Vec<&str> = args.iter().map(|s| s.as_str()).collect();
        let (stdout, stderr, status) = run(&args_refs);
        if *expect_success {
            assert!(
                status.success(),
                "Expected success for {:?}\nstdout: {}\nstderr: {}",
                args_refs,
                stdout,
                stderr
            );
        }
        assert_json_object_output(&args_refs, &stdout);
    }
}
