[package]
name = "pkms-web"
version = "2.4.2"
description = "Local web viewer for pkms notes"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = "1"
katex = "0.4.6"
pkms-org = { path = "../pkms-org" }
pulldown-cmark = "0.13.4"
regex = "1"
serde = { version = "1", features = ["derive"] }
syntect = "5.3.0"
tracing = "0.1"

[dev-dependencies]
tempfile = "3"
